# Permalinks
permalink:           pretty

# Setup
title:               GChoi
tagline:             Geunho Choi
url:                 http://cgh2797.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Geunho Choi
  url:               https://twitter.com/inu_cgh
  email:             cgh2797@naver.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/cgh2797

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
